//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projeEntities : DbContext
    {
        public projeEntities()
            : base("name=projeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetayTanimlari> DetayTanimlaris { get; set; }
        public virtual DbSet<KampanyaBanner> KampanyaBanners { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<SiparisDetay> SiparisDetays { get; set; }
        public virtual DbSet<SiparisDurumlari> SiparisDurumlaris { get; set; }
        public virtual DbSet<Siparislerim> Siparislerims { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<UrunDetaylari> UrunDetaylaris { get; set; }
        public virtual DbSet<UrunKategorileri> UrunKategorileris { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
        public virtual DbSet<UrunResimleri> UrunResimleris { get; set; }
        public virtual DbSet<UrunYorumlari> UrunYorumlaris { get; set; }
        public virtual DbSet<Uyeler> Uyelers { get; set; }
    }
}
