//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class KampanyaBanner
    {
        public int bannerID { get; set; }
        public string bannerResim { get; set; }
        public string bannerAciklama { get; set; }
        public Nullable<System.DateTime> bannerTarih { get; set; }
        public Nullable<bool> aktiflik { get; set; }
    }
}
