//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparislerim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparislerim()
        {
            this.SiparisDetays = new HashSet<SiparisDetay>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<int> UyeID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> SiparisDurumu { get; set; }
        public Nullable<double> Tutar { get; set; }
        public Nullable<int> KargoFirmai { get; set; }
        public Nullable<double> KargoTutari { get; set; }
        public Nullable<double> ToplamTutar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetays { get; set; }
    }
}
